## Continents
# Asia
southern_asia = ["AFG", "BGD", "BTN", "IND", "IRN", "LKA", "MDV", "NPL", "PAK"]
western_asia = ["ARE", "ARM", "AZE", "BHR", "CYP", "GEO", "IRQ", "ISR", "JOR", "KWT", "LBN", "OMN", "PSE", "QAT", "SAU", "SYR", "TUR", "YEM", "YMD", "YMN"]
southeastern_asia = ["BRN", "IDN", "KHM", "LAO", "MMR", "MYS", "PHL", "SGP", "THA", "VNM", "TLS"]
eastern_asia = ["CHN", "HKG", "JPN", "KOR", "MAC", "MNG", "PRK", "TWN"]
central_asia = ["KAZ", "KGZ", "TJK", "TKM", "UZB"]
asia = southern_asia + western_asia + southeastern_asia + eastern_asia + central_asia

# Africa
middle_africa = ["AGO", "CAF", "CMR", "COG", "GAB", "GNQ", "STP", "TCD", "COD"]
eastern_africa = ["BDI", "COM", "DJI", "ERI", "ETH", "KEN", "MDG", "MOZ", "MUS", "MWI", "REU", "RWA", "SOM", "SYC", "TZA", "UGA", "ZMB", "ZWE", "MYT", "ATF", "IOT"]
western_africa = ["BEN", "BFA", "CIV", "CPV", "GHA", "GIN", "GMB", "GNB", "LBR", "MLI", "MRT", "NER", "NGA", "SEN", "SHN", "SLE", "TGO"]
southern_africa = ["BWA", "LSO", "NAM", "SWZ", "ZAF"]
northern_africa = ["DZA", "EGY", "ESH", "LBY", "MAR", "SDN", "TUN", "SSD"]
africa = middle_africa + eastern_africa + western_africa + southern_africa + northern_africa

# Americas
caribbean = ["AIA", "ANT", "ATG", "BHS", "BRB", "CUB", "CYM", "DMA", "DOM", "GLP", "GRD", "HTI", "JAM", "KNA", "LCA", "MSR", "MTQ", "PRI", "TCA", "TTO", "VCT", "VGB", "VIR", "ABW", "BES", "BLM", "CUW", "MAF", "SXM"]
south_america = ["ARG", "BOL", "BRA", "CHL", "COL", "ECU", "FLK", "GUF", "GUY", "PER", "PRY", "SUR", "URY", "VEN", "BVT", "SGS"]
central_america = ["BLZ", "CRI", "GTM", "HND", "MEX", "NIC", "PAN", "SLV"]
northern_america = ["BMU", "CAN", "GRL", "SPM", "USA"]
americas = caribbean + south_america + central_america + northern_america

# Europe
southern_europe = ["ALB", "AND", "AZO", "BIH", "ESP", "GIB", "GRC", "HRV", "ITA", "MKD", "MLT", "PRT", "SMR", "SPI", "SCG", "SVN", "VAT", "YUG", "SRB", "MNE"]
western_europe = ["AUT", "BEL", "CHE", "DDR", "DEU", "DFR", "FRA", "LIE", "LUX", "MCO", "NLD"]
eastern_europe = ["BGR", "BLR", "CSK", "CZE", "HUN", "MDA", "POL", "ROU", "RUS", "SVK", "UKR"]
northern_europe = ["CHA", "DNK", "EST", "FIN", "FRO", "GBR", "IRL", "ISL", "LTU", "LVA", "IMN", "NOR", "SWE", "SJM", "ALA", "GGY", "JEY"]
russian_federation = ["SUN"]
europe = southern_europe + western_europe + eastern_europe + northern_europe + russian_federation

# Oceania
polynesia = ["ASM", "COK", "NIU", "PCN", "PYF", "TKL", "TON", "TUV", "WLF", "WSM"]
australia_new_zealand = ["AUS", "NZL", "NFK", "CCK", "CXR", "HMD"]
melanesia = ["FJI", "NCL", "PNG", "SLB", "VUT"]
micronesia = ["FSM", "GUM", "KIR", "MHL", "NRU", "PLW", "MNP", "UMI"]
oceania = polynesia + australia_new_zealand + melanesia + micronesia


#'CHA' - northern_europe - unknown
# Dictionary of each country
countries_dict = {
    "AFG":"Afghanistan",
    "ALA":"Aland Islands",
    "ALB":"Albania",
    "DZA":"Algeria",
    "ASM":"American Samoa",
    "AND":"Andorra",
    "AGO":"Angola",
    "AIA":"Anguilla",
    "ATG":"Antigua and Barbuda",
    "ARG":"Argentina",
    "ARM":"Armenia",
    "ABW":"Aruba",
    "AUS":"Australia",
    "AUT":"Austria",
    "AZE":"Azerbaijan",
    "AZO":"Azores Islands",
    "BHS":"Bahamas",
    "BHR":"Bahrain",
    "BGD":"Bangladesh",
    "BRB":"Barbados",
    "BLR":"Belarus",
    "BEL":"Belgium",
    "BLZ":"Belize",
    "BEN":"Benin",
    "BMU":"Bermuda",
    "BTN":"Bhutan",
    "BOL":"Bolivia",
    "BES":"Bonaire, Sint Eustatius and Saba",
    "BIH":"Bosnia and Herzegovina",
    "BWA":"Botswana",
    "BVT":"Bouvet Island",
    "BRA":"Brazil",
    "IOT":"British Indian Ocean Territory",
    "BRN":"Brunei Darussalam",
    "BGR":"Bulgaria",
    "BFA":"Burkina Faso",
    "BDI":"Burundi",
    "CPV":"Cabo Verde",
    "KHM":"Cambodia",
    "CMR":"Cameroon",
    "CAN":"Canada",
    "SPI":"Canary Islands",
    "CYM":"Cayman Islands",
    "CAF":"Central African Republic",
    "TCD":"Chad",
    "CHL":"Chile",
    "CHN":"China",
    "CXR":"Christmas Island",
    "CCK":"Cocos Islands",
    "COL":"Colombia",
    "COM":"Comoros",
    "COD":"Democratic Republic of Congo",
    "YMD":"Democratic Yemen",
    "COG":"Congo",
    "COK":"Cook Islands",
    "CRI":"Costa Rica",
    "CIV":"Cote d'Ivoire",
    "HRV":"Croatia",
    "CUB":"Cuba",
    "CUW":"Curacao",
    "CYP":"Cypress",
    "CZE":"Czech Republic",
    "CSK":"Czechoslovakia",
    "DNK":"Denmark",
    "DJI":"Djibouti",
    "DMA":"Dominica",
    "DOM":"Dominican Republic",
    "ECU":"Ecuador",
    "EGY":"Egypt",
    "SLV":"El Salvador",
    "GNQ":"Equatorial Guinea",
    "ERI":"Eritrea",
    "EST":"Estonia",
    "SWZ":"Eswatini",
    "ETH":"Ethiopia",
    "FLK":"Falkland Islands",
    "FRO":"Faroe Islands",
    "FJI":"Fiji",
    "FIN":"Finland",
    "FRA":"France",
    "GUF":"French Guiana",
    "PYF":"French Polynesia",
    "ATF":"French Southern Territories",
    "GAB":"Gabon",
    "GMB":"Gambia",
    "GEO":"Georgia",
    "DEU":"Germany",
    "DDR":"Germany Democratic Republic",
    "DFR":"Germany Federal Republic",
    "GHA":"Ghana",
    "GIB":"Gibraltar",
    "GRC":"Greece",
    "GRL":"Greenland",
    "GRD":"Grenada",
    "GLP":"Guadeloupe",
    "GUM":"Guam",
    "GTM":"Guatemala",
    "GGY":"Guernsey",
    "GIN":"Guinea",
    "GNB":"Guinea-Bissau",
    "GUY":"Guyana",
    "HTI":"Haiti",
    "HMD":"Heard and McDonald Islands",
    "VAT":"Holy See",
    "HND":"Honduras",
    "HKG":"Hong Kong",
    "HUN":"Hungary",
    "ISL":"Iceland",
    "IND":"India",
    "IDN":"Indonesia",
    "IRN":"Iran",
    "IRQ":"Iraq",
    "IRL":"Ireland",
    "IMN":"Isle of Man",
    "ISR":"Israel",
    "ITA":"Italy",
    "JAM":"Jamaica",
    "JPN":"Japan",
    "JEY":"Jersey",
    "JOR":"Jordan",
    "KAZ":"Kazakhstan",
    "KEN":"Kenya",
    "KIR":"Kiribati",
    "PRK":"Democratic People of Korea",
    "KOR":"Korea",
    "KWT":"Kuwait",
    "KGZ":"Kyrgyzstan",
    "LAO":"Lao",
    "LVA":"Latvia",
    "LBN":"Lebanon",
    "LSO":"Lesotho",
    "LBR":"Liberia",
    "LBY":"Libya",
    "LIE":"Liechtenstein",
    "LTU":"Lithuania",
    "LUX":"Luxembourg",
    "MAC":"Macao",
    "MKD":"North Macedonia",
    "MDG":"Madagascar",
    "MWI":"Malawi",
    "MYS":"Malaysia",
    "MDV":"Maldives",
    "MLI":"Mali",
    "MLT":"Malta",
    "MHL":"Marshall Islands",
    "MTQ":"Martinique",
    "MRT":"Mauritania",
    "MUS":"Mauritius",
    "MYT":"Mayotte",
    "MEX":"Mexico",
    "FSM":"Micronesia",
    "MDA":"Moldova",
    "MCO":"Monaco",
    "MNG":"Mongolia",
    "MNE":"Montenegro",
    "MSR":"Montserrat",
    "MAR":"Morocco",
    "MOZ":"Mozambique",
    "MMR":"Myanmar",
    "NAM":"Namibia",
    "NRU":"Nauru",
    "NPL":"Nepal",
    "NLD":"Netherlands",
    "ANT":"Netherlands Antilles",
    "NCL":"New Caledonia",
    "NZL":"New Zealand",
    "NIC":"Nicaragua",
    "NER":"Niger",
    "NGA":"Nigeria",
    "NIU":"Niue",
    "NFK":"Norfolk Island",
    "MNP":"Northern Mariana Islands",
    "NOR":"Norway",
    "OMN":"Oman",
    "PAK":"Pakistan",
    "PLW":"Palau",
    "PSE":"Palestine",
    "PAN":"Panama",
    "PNG":"Papua New Guinea",
    "PRY":"Paraguay",
    "PER":"Peru",
    "PHL":"Philippines",
    "PCN":"Pitcairn",
    "POL":"Poland",
    "PRT":"Portugal",
    "PRI":"Puerto Rico",
    "QAT":"Qatar",
    "REU":"Reunion",
    "ROU":"Romania",
    "RUS":"Russia",
    "RWA":"Rwanda",
    "BLM":"Saint Barthelemy",
    "SHN":"Saint Helena, Ascension Island and Tristan da Cunha",
    "KNA":"Saint Kitts and Nevis",
    "LCA":"Saint Lucia",
    "MAF":"Saint Martin",
    "SPM":"Saint Pierre and Miquelon",
    "VCT":"Saint Vincent and Grenadines",
    "WSM":"Samoa",
    "SMR":"San Marino",
    "STP":"Sao Tome and Principe",
    "SAU":"Saudi Arabia",
    "SEN":"Senegal",
    "SRB":"Serbia",
    "SCG":"Serbia and Montenegro",
    "SYC":"Seychelles",
    "SLE":"Sierra Leone",
    "SGP":"Singapore",
    "SXM":"Sint Maarten",
    "SVK":"Slovakia",
    "SVN":"Slovenia",
    "SLB":"Solomon Islands",
    "SOM":"Somalia",
    "ZAF":"South Africa",
    "SGS":"South Georgia and the South Sandwich Islands",
    "SSD":"South Sudan",
    "SUN":"Soviet Union",
    "ESP":"Spain",
    "LKA":"Sri Lanka",
    "SDN":"Sudan",
    "SUR":"Suriname",
    "SJM":"Svalbard and Jan Mayen",
    "SWE":"Sweden",
    "CHE":"Switzerland",
    "SYR":"Syria",
    "TWN":"Taiwan",
    "TJK":"Tajikistan",
    "TZA":"Tanzania",
    "THA":"Thailand",
    "TLS":"Timor-Leste",
    "TGO":"Togo",
    "TKL":"Tokelau",
    "TON":"Tonga",
    "TTO":"Trinidad and Tobago",
    "TUN":"Tunisia",
    "TUR":"Turkey",
    "TKM":"Turkmenistan",
    "TCA":"Turks and Caicos Islands",
    "TUV":"Tuvalu",
    "UGA":"Uganda",
    "UKR":"Ukraine",
    "ARE":"United Arab Emirates",
    "CHA":"Unknown",
    "GBR":"Great Britain and Northern Ireland",
    "UMI":"United Stated Minor Outlying Islands",
    "USA":"United States of America",
    "URY":"Uruguay",
    "UZB":"Uzbekistan",
    "VUT":"Vanuatu",
    "VEN":"Venezuela",
    "VNM":"Viet Nam",
    "VGB":"British Virgin Islands",
    "VIR":"US Virgin Islands",
    "WLF":"Wallis and Futuna Islands",
    "ESH":"Western Sahara",
    "YMN":"Yemen Arab Republic",
    "YEM":"Yemen Democratic Republic",
    "YUG":"Yugoslavia",
    "ZMB":"Zambia",
    "ZWE":"Zimbabwe"}
